const images = {
  adidas: require("../../assets/images/onBoarding/adidas.png"),
  BlackOval: require("../../assets/images/onBoarding/BlackOval.png"),
  GreenOval: require("../../assets/images/onBoarding/GreenOval.png"),
  CK: require("../../assets/images/onBoarding/CK.png"),
  nike: require("../../assets/images/onBoarding/nike.png"),
  Smith: require("../../assets/images/onBoarding/Smith.png"),
  undrawOnlineShopping: require("../../assets/images/onBoarding/undrawOnlineShopping.png"),
  Wallet: require("../../assets/images/onBoarding/Wallet.png"),
  OnBoardingSecondScreenBack: require("../../assets/images/onBoarding/OnBoardinSecondScreenBack.png"),
  OnBoardingThirdScreen: require("../../assets/images/onBoarding/OnBoardingThirdScreen.png"),
  OnBoardingFourthScreen: require("../../assets/images/onBoarding/OnBoardingFourthScreen.png"),

  BelowFB: require("../../assets/images/auth/BelowFB.png"),
  email: require("../../assets/images/auth/email.png"),
  FB: require("../../assets/images/auth/FB.png"),
  ZoopKart: require("../../assets/images/auth/ZoopKart.png"),
  Google: require("../../assets/images/auth/Google.png"),
  Location: require("../../assets/images/auth/Location.png"),

  Search: require("../../assets/images/Shop/Home/iconSearch.png"),
  menu: require("../../assets/images/Shop/Home/menu.png"),
  SlidingHeaderOne: require("../../assets/images/Shop/Home/SlidingHeaderOne.png"),
  ZoopKartTextLogo: require("../../assets/images/Shop/Home/ZoopKartTextLogo.png"),
  CatTop: require("../../assets/images/Shop/Home/CatTop.png"),
  Next: require("../../assets/images/Shop/Home/Next.png"),
  BrandNumber: require("../../assets/images/Shop/Home/BrandNumber.png"),
  BackArrow: require("../../assets/images/Shop/Home/BackArrow.png"),
  Filter: require("../../assets/images/Shop/Home/Filter.png"),
  Sort: require("../../assets/images/Shop/Home/Sort.png"),
  Circle: require("../../assets/images/Shop/Home/Circle.png"),
  Cross: require("../../assets/images/Shop/Home/Cross.png"),
  Rating: require("../../assets/images/Shop/Home/Rating.png"),
  MobileOne: require("../../assets/images/Shop/Home/MobileOne.png"),
  Add: require("../../assets/images/Shop/Home/Add.png"),
  Remove: require("../../assets/images/Shop/Home/Remove.png"),
  NoOfItems: require("../../assets/images/Shop/Home/NoOfItem.png"),
  Fee: require("../../assets/images/Shop/Home/Fee.png"),
  ColoredClose: require("../../assets/images/Shop/Home/ColoredClose.png"),
  SlidingHeaderOne: require("../../assets/images/Shop/Home/SlidingHeaderOne.png"),
  Deals: require("../../assets/images/Shop/Home/Deals.png"),
  Pantry: require("../../assets/images/Shop/Home/Pantry.png"),
  Speaker: require("../../assets/images/Shop/Home/Speaker.png"),
  Sports: require("../../assets/images/Shop/Home/Sports.png"),
  Makeup: require("../../assets/images/Shop/Home/Makeup.png"),
  Hair: require("../../assets/images/Shop/Home/Hair.png"),
  Earphone: require("../../assets/images/Shop/Home/Earphone.png"),
  Watch: require("../../assets/images/Shop/Home/Watch.png"),
  Rating: require("../../assets/images/Shop/Home/Rating.png"),
  MobileOne: require("../../assets/images/Shop/Home/MobileOne.png"),
  MobileTwo: require("../../assets/images/Shop/Home/MobileTwo.png"),
  MobileThree: require("../../assets/images/Shop/Home/MobileThree.png"),
  Fragrance: require("../../assets/images/Shop/Home/Makeup.png"),
  Trekking: require("../../assets/images/Shop/Home/Trekking.png"),
  Formal: require("../../assets/images/Shop/Home/Sports.png")
};

export default images;
